with:
  version: v1.56.2
  install-mode: binary
  github-token: ${{ secrets.GITHUB_TOKEN }}
  only-new-issues: false
  skip-cache: false
  skip-save-cache: false
  problem-matchers: false
  cache-invalidation-interval: 7
